### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by mengxn** [ChrisZou/android-unit-testing-tutorial#3]
《Android单元测试: 首先，从是什么开始》
1、所以，写单元测试，就是给你的每个类的每个public方法写对于（应）的测试方法。

2、如果这是一句牢骚的话，就放括号（）里吧
因为AndroidStudio太智能了，经常我需要重命名单元测试的package的时候，AndroidStudio会把src的package也给重命名了。

**Comment by ChrisZou** [comment]
谢谢反馈，已经fix了。

**Comment by ChrisZou** [comment]
谢谢反馈，已经fix了。
