### ISSUE TITLE
dagger..看得我尴尬症都犯了

### ISSUE THREAD

**Issue by vipheyue** [ChrisZou/android-unit-testing-tutorial#4]

**Comment by ChrisZou** [comment]
为什么呢？

**Comment by vipheyue** [comment]
直接把AppComponent  -> LoginActivity 还是不建议把全局的Component 直接给具体的 Activity.
容易误导其他来看这个项目的人

**Comment by ChrisZou** [comment]
“把全局的Component 直接给具体的 Activity”？不是很明白你的意思，能具体讲讲吗？
如果有误导人的地方，我很抱歉，不过目前还没明白是哪里有问题呢？

**Comment by vipheyue** [comment]
你这个项目是测试 单独运行 没什么问题.
我看了一下代码. LoginActivity 需要的 对象或者数据  是通过 AppComponent 来注入的.
按照规范是因该通过 LoginComponent 来注入. 
因为 如果LoginActivity需要更多的对象 我们因该在 LoginModule 里面提供..并使用 LoginComponent 来注入
而不是跑到AppComponent 里面去添加 LoginModule,这样会使得AppComponent变得非常的杂乱

**Comment by ChrisZou** [comment]
@vipheyue 谢谢你的反馈，明白你的意思了，你说的问题是关于deps太多、Module太大的情况下，怎么样划分多Module来合理的管理这些deps，这个是在熟悉dagger使用的前提下，再进一步的问题。而这篇文章的目标读者是不熟悉Dagger基本使用的人，希望能给一个基础的使用入门以及工作原理的介绍，并没有想过要一口气吃成大胖子，因此没有考虑太多其它并不是那么直接相关的问题。
