### ISSUE TITLE
异步单元测试运行走不到testLoadRepos()里面的callback

### ISSUE THREAD

**Issue by mistakelijc** [ChrisZou/android-unit-testing-tutorial#5]
运行RepoModelTest，测试testLoadRepos()方法，发现它会一直在await，结束不了。后来加入log后发现代码没有走到callback的onSuccess里面，所以没有触发latch.countDown()。跟进去RepoModel里面发现是callback.onSuccess(repos)调用的问题，直接调用的话后面是能够运行到callback的onSuccess里面的；但是如果用mUiHandler.post()来调用的话就执行不到run()里面的内容了，这是为什么呢？

**Comment by ChrisZou** [comment]
Handler post出来的信息不会被Robolectric立刻执行。你需要
调用一下`ShadowLooper.runUiThreadTasksIncludingDelayedTasks`。参考 https://stackoverflow.com/questions/18956117/robolectric-run-handler-post
