### ISSUE TITLE
关于目录完整性的问题

### ISSUE THREAD

**Issue by LonelyMushroom** [ChrisZou/android-unit-testing-tutorial#7]
你的md里面好像少了目录2和目录7

**Comment by imknown** [comment]
- Android单元测试（二）：再来谈谈为什么
http://www.jianshu.com/p/68212278f592

- Android单元测试(七)：Robolectric，在JVM上调用安卓的类
http://www.jianshu.com/p/14a2f7ca89f4

**Comment by LonelyMushroom** [comment]
@imknown 其实我的意思是更改下README.md这个文件，添加上去。谢谢啦

**Comment by imknown** [comment]
@LonelyMushroom 开个 pr 吧, 不知道 owner 能不能 merge..
